server:
  port: 8081
spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/profile_travel_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.travelsmart.profile_service.config.CustomSerializer
    consumer:

      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.travelsmart.profile_service.config.CustomDeserializer
      specific:

        value:
          default-type: com.travelsmart.event.dto.ProfileRequest  # Chỉ định class sẽ được deserialize
      properties:
        spring.json.trusted.packages: "*"
api:
  prefix: /profile/api/v1
token:
  tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  accessExpiration: 1500000
  refreshExpiration: 604800000
